import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Providers from "@/components/providers/PrivyProvider";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

export const metadata: Metadata = {
  title: "FundioVC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
